### ISSUE TITLE
Task.05 Create 2 Database Tables to store user login information

### ISSUE THREAD

**Issue by R-Mauricio13** [R-Mauricio13/Group-24-SOEN341_Project_F24#5]
Need to store all login information

**Comment by VladimirTodorov21** [comment]
Table user_student has been created containing:

- 1) std_user_id as an integer (Primary Key)
- 2) first_name as a string
- 3) last_name as a string
- 4) username as a string
- 5) email as a string
- 6) pwd as a string (password)

**Comment by VladimirTodorov21** [comment]
Table user_instructor has been created containing:

- 1) ins_user_id as an integer (Primary Key)
- 2) first_name as a string
- 3) last_name as a string
- 4) username as a string
- 5) email as a string
- 6) pwd as a string (password)
