### ISSUE TITLE
Task.06 Create Database Table to store each team

### ISSUE THREAD

**Issue by R-Mauricio13** [R-Mauricio13/Group-24-SOEN341_Project_F24#6]
Each team should contain:

1.  Team Name
2.  Students inside the team (with id and name of said students)
3. Team size

**Comment by VladimirTodorov21** [comment]
Table student_groups created containing:

- 1) group_id as integer
- 2) group_name as string
- 3) user_id as foreign key referenced from user_student table's std_user_id
